/** Canonical peer-set firms from config/watchlists.yaml (stated focus for drift detection). */
export type PeerFirmConfig = {
  name: string;
  aliases: string[];
  stated_focus: string;
};

export const PEER_FIRMS: PeerFirmConfig[] = [
  { name: "Andreessen Horowitz", aliases: ["a16z"], stated_focus: "AI, bio, crypto, fintech, games, infra" },
  { name: "Sequoia Capital", aliases: ["Sequoia"], stated_focus: "Multi-stage technology" },
  { name: "Lux Capital", aliases: ["Lux"], stated_focus: "Deep tech, frontier science" },
  { name: "Conviction", aliases: [], stated_focus: "AI application layer" },
  { name: "Gradient Ventures", aliases: [], stated_focus: "AI-first startups" },
  { name: "Ribbit Capital", aliases: ["Ribbit"], stated_focus: "Fintech" },
  { name: "Shield Capital", aliases: [], stated_focus: "National security, cyber, space" },
  { name: "8VC", aliases: [], stated_focus: "Bio, defense, enterprise" },
  { name: "Thrive Capital", aliases: ["Thrive"], stated_focus: "Internet, software, fintech" },
  { name: "Redpoint", aliases: [], stated_focus: "Enterprise, consumer, crypto" },
  { name: "Altimeter Capital", aliases: ["Altimeter"], stated_focus: "Growth tech" },
  { name: "Coatue Management", aliases: ["Coatue"], stated_focus: "Growth tech, public/private" },
  { name: "Tiger Global Management", aliases: ["Tiger Global", "Tiger"], stated_focus: "Growth internet" },
  { name: "IVP", aliases: ["Institutional Venture Partners"], stated_focus: "Growth-stage technology" },
  { name: "Bessemer Venture Partners", aliases: ["Bessemer"], stated_focus: "Cloud, vertical SaaS, fintech" },
  { name: "Insight Partners", aliases: ["Insight"], stated_focus: "Scale-up software" },
  { name: "Founders Fund", aliases: [], stated_focus: "Frontier tech, aerospace, AI" },
  { name: "Lightspeed Venture Partners", aliases: ["Lightspeed"], stated_focus: "Enterprise, consumer, health, fintech" },
  { name: "Khosla Ventures", aliases: ["Khosla"], stated_focus: "Climate, AI, health, frontier" },
  { name: "Spark Capital", aliases: ["Spark"], stated_focus: "Consumer, enterprise, crypto" },
  { name: "Benchmark", aliases: [], stated_focus: "Early-stage technology" },
  { name: "Accel", aliases: [], stated_focus: "Multi-stage technology" },
  { name: "General Catalyst", aliases: [], stated_focus: "Multi-stage, transformation" },
  { name: "Y Combinator", aliases: ["YC"], stated_focus: "Early-stage seed" },
  { name: "Felicis Ventures", aliases: ["Felicis"], stated_focus: "Early-stage technology" },
  { name: "Initialized Capital", aliases: ["Initialized"], stated_focus: "Seed" },
  { name: "Index Ventures", aliases: ["Index"], stated_focus: "Multi-stage" },
  { name: "GV", aliases: ["Google Ventures"], stated_focus: "Multi-stage" },
  { name: "NEA", aliases: [], stated_focus: "Multi-stage" },
  { name: "Kleiner Perkins", aliases: [], stated_focus: "Multi-stage" },
  { name: "Peak XV Partners", aliases: ["Peak XV"], stated_focus: "India / SEA technology" },
  { name: "NFX", aliases: [], stated_focus: "Network effects" },
  { name: "Dragonfly", aliases: [], stated_focus: "Crypto" },
  { name: "Picus Capital", aliases: [], stated_focus: "Early-stage Europe" },
  { name: "Basis Set Ventures", aliases: [], stated_focus: "AI automation" },
  { name: "Kindred Ventures", aliases: [], stated_focus: "Seed technology" },
  { name: "Antler", aliases: [], stated_focus: "Day-zero founding" },
  { name: "Entrepreneurs First", aliases: ["EF"], stated_focus: "Talent-first founding" },
  { name: "Obvious Ventures", aliases: [], stated_focus: "World-positive companies" },
  { name: "Primary Venture Partners", aliases: ["Primary"], stated_focus: "NYC early-stage" },
  { name: "137 Ventures", aliases: [], stated_focus: "Late-stage secondary" },
  { name: "Seraphim Space", aliases: [], stated_focus: "Space tech" },
  { name: "Quantonation Ventures", aliases: ["Quantonation"], stated_focus: "Quantum technologies" },
  { name: "Breakout Ventures", aliases: [], stated_focus: "Deep science" },
  { name: "Scout Ventures", aliases: [], stated_focus: "Early-stage" },
  { name: "2048 Ventures", aliases: [], stated_focus: "Pre-seed deep tech" },
  { name: "Voyager Ventures", aliases: [], stated_focus: "Climate / energy" },
  { name: "Sante Ventures", aliases: ["Santé Ventures", "Sante"], stated_focus: "Healthcare" },
  { name: "StageOne Ventures", aliases: [], stated_focus: "Israeli enterprise" },
  { name: "b2venture", aliases: [], stated_focus: "European early-stage" },
  { name: "Social Leverage", aliases: [], stated_focus: "Fintech / consumer" },
  { name: "Layer Global", aliases: [], stated_focus: "Crypto infrastructure" },
  { name: "Rosberg Ventures", aliases: [], stated_focus: "Early-stage" },
  { name: "CAVU Consumer Partners", aliases: [], stated_focus: "Consumer" },
  { name: "CoFound", aliases: [], stated_focus: "Early-stage" },
  { name: "Haystack", aliases: [], stated_focus: "Seed" },
  { name: "Silver Lake", aliases: [], stated_focus: "Tech private equity" },
  { name: "Union Square Ventures", aliases: ["USV"], stated_focus: "Thesis-driven technology" },
  { name: "SlateVC", aliases: [], stated_focus: "Early-stage" },
  { name: "Samaipata", aliases: [], stated_focus: "European marketplace / fintech" },
  { name: "1752vc", aliases: ["1752"], stated_focus: "Early-stage technology" },
  { name: "Greylock", aliases: [], stated_focus: "Enterprise, consumer, crypto" },
];
