/**
 * Embedded prefill pack for Continuous Deal Sourcing.
 * Mirrors seed_corpus signals so /source works before Refresh / without Gemini.
 * Replace/augment via Python adapters when SIGNAL_SOURCING_MODE=live|hybrid.
 */

import type { SignalItem } from "@/lib/types";

export const PREFILL_SOURCING_SIGNALS: SignalItem[] = [
  {
    id: "sig1",
    company_id: "c_agentgate",
    company_name: "AgentGate",
    source: "seed",
    signal_type: "funding",
    title: "AgentGate Series A led by Greylock",
    summary: "Identity for AI agents raises $48M — Greylock leads; Tier-1 crowded.",
    observed_at: "2026-06-25",
    raw: { prefill: true, early_signal: false, mainstream: true },
  },
  {
    id: "sig3",
    company_id: "c_modnuc",
    company_name: "Modular Nucleus",
    source: "seed",
    signal_type: "funding",
    title: "Modular Nucleus raise",
    summary: "SMR software for AI data centers closes strategic round.",
    observed_at: "2026-07-12",
    raw: { prefill: true, early_signal: false, mainstream: true },
  },
  {
    id: "sig_fund_quietpath",
    company_id: "c_quietrobot",
    company_name: "QuietPath Robotics",
    source: "prefill:form_d",
    signal_type: "funding",
    title: "QuietPath Robotics Form D — $6.2M seed (pre-announce)",
    summary: "Warehouse autonomy seed not yet on PitchBook league tables — early regulatory signal.",
    url: "https://www.sec.gov/edgar/searchedgar/companysearch",
    observed_at: "2026-08-06",
    raw: { prefill: true, early_signal: true, mainstream: false },
  },
  {
    id: "sig_fund_idforge",
    company_id: "c_idforge",
    company_name: "IDForge Labs",
    source: "prefill:angel_list",
    signal_type: "funding",
    title: "IDForge Labs closes $4M angel+seed for agent identity primitives",
    summary: "Off-radar identity infra for agentic workflows; no Tier-1 lead yet.",
    observed_at: "2026-08-05",
    raw: { prefill: true, early_signal: true, mainstream: false },
  },
  {
    id: "sig_fund_idforge_hn",
    company_id: "c_idforge",
    company_name: "IDForge Labs",
    source: "prefill:hn",
    signal_type: "funding",
    title: "IDForge Labs closes $4M angel+seed for agent identity primitives",
    summary: "HN thread mirrors angel round rumor — same raise as AngelList hit.",
    url: "https://news.ycombinator.com/",
    observed_at: "2026-08-05",
    raw: { prefill: true, early_signal: true, mainstream: false },
  },
  {
    id: "sig_fund_latticenova",
    company_name: "LatticeNova",
    source: "prefill:hn",
    signal_type: "funding",
    title: "LatticeNova raises seed for inference optimization GPUs",
    summary: "Edge inference startup building small language model runtimes — not on CB hot lists yet.",
    url: "https://news.ycombinator.com/",
    observed_at: "2026-08-09",
    raw: { prefill: true, early_signal: true, mainstream: false },
  },
  {
    id: "sig_hire_gpumesh",
    company_id: "c_gpumesh",
    company_name: "GPUMesh",
    source: "prefill:hiring_proxy",
    signal_type: "hiring",
    title: "GPUMesh hiring spike — 18 inference eng roles in 30 days",
    summary: "Headcount proxy: cluster scheduling + CUDA kernel roles; growth signal ahead of next raise.",
    observed_at: "2026-08-08",
    raw: { prefill: true, early_signal: false, mainstream: true },
  },
  {
    id: "sig_hire_evalfarm",
    company_id: "c_evalfarm",
    company_name: "EvalFarm",
    source: "prefill:hiring_proxy",
    signal_type: "hiring",
    title: "EvalFarm opens first GTM + eval researcher seats",
    summary: "Stealth-ish eval infra co adding GTM — early org-build signal, still off Tier-1 radar.",
    observed_at: "2026-08-07",
    raw: { prefill: true, early_signal: true, mainstream: false },
  },
  {
    id: "sig_hire_swarm",
    company_id: "c_swarmguard",
    company_name: "SwarmGuard",
    source: "prefill:hiring_proxy",
    signal_type: "hiring",
    title: "SwarmGuard posting CUAS autonomy + RF eng roles",
    summary: "Defence hiring pattern consistent with fielded pilots expanding.",
    observed_at: "2026-08-04",
    raw: { prefill: true, early_signal: false, mainstream: true },
  },
  {
    id: "sig2",
    company_id: "c_agentide",
    company_name: "AgentIDE",
    source: "hn",
    signal_type: "product_launch",
    title: "Show HN: AgentIDE",
    summary: "Viral launch for agent-native IDE — product heat before Series B chatter.",
    url: "https://news.ycombinator.com/",
    observed_at: "2026-08-07",
    raw: { prefill: true, early_signal: false, mainstream: false },
  },
  {
    id: "sig_launch_voicewire",
    company_id: "c_voicewire",
    company_name: "VoiceWire",
    source: "prefill:producthunt",
    signal_type: "product_launch",
    title: "VoiceWire GA — low-latency voice agents for enterprise support",
    summary: "Generally available multimodal voice stack; first public SKU.",
    observed_at: "2026-08-03",
    raw: { prefill: true, early_signal: false, mainstream: false },
  },
  {
    id: "sig_launch_orbit",
    company_id: "c_orbitlens",
    company_name: "OrbitLens",
    source: "prefill:rss",
    signal_type: "product_launch",
    title: "OrbitLens ships v0.9 satellite change-detection API",
    summary: "Defence-adjacent product launch; limited press, high thesis fit.",
    observed_at: "2026-08-02",
    raw: { prefill: true, early_signal: true, mainstream: false },
  },
  {
    id: "sig4",
    company_id: "c_synthforge",
    company_name: "SynthForge",
    source: "seeded_social",
    signal_type: "founder_move",
    title: "Watched founder (ex-DeepMind) launching stealth RL environment co — flagged by Elad Gil",
    summary: "GP watchlist hit: founder newco matching AI infra thesis",
    url: "https://x.com/eladgil",
    observed_at: "2026-08-08",
    raw: { prefill: true, early_signal: true, mainstream: false },
  },
  {
    id: "sig_founder_shadow",
    company_name: "ShadowRelay",
    source: "prefill:gp_watchlist",
    signal_type: "founder_move",
    title: "Ex-Palantir + Anduril operators spinning up ShadowRelay (CUAS data fusion)",
    summary: "Watched operator newco — defence thesis, no public raise yet.",
    observed_at: "2026-08-09",
    raw: { prefill: true, early_signal: true, mainstream: false },
  },
  {
    id: "sig_founder_shadow_x",
    company_name: "ShadowRelay",
    source: "prefill:social",
    signal_type: "founder_move",
    title: "Ex-Palantir + Anduril operators spinning up ShadowRelay (CUAS data fusion)",
    summary: "Social corroboration of same founder move — consolidate with GP watchlist hit.",
    observed_at: "2026-08-09",
    raw: { prefill: true, early_signal: true, mainstream: false },
  },
  {
    id: "sig_cust_lattice",
    company_id: "c_latticeeval",
    company_name: "LatticeEval",
    source: "prefill:press",
    signal_type: "customer_win",
    title: "LatticeEval lands second frontier-lab eval contract",
    summary: "Named (redacted) lab expansion — traction without a fresh raise headline.",
    observed_at: "2026-08-06",
    raw: { prefill: true, early_signal: false, mainstream: true },
  },
  {
    id: "sig_cust_forgebot",
    company_id: "c_forgebot",
    company_name: "ForgeBot",
    source: "prefill:press",
    signal_type: "customer_win",
    title: "ForgeBot wins first auto OEM pilot for factory cell robotics",
    summary: "Customer win in AI manufacturing — early commercial proof.",
    observed_at: "2026-08-01",
    raw: { prefill: true, early_signal: true, mainstream: false },
  },
  {
    id: "sig_cust_railbank",
    company_id: "c_railbank",
    company_name: "RailBank Infra",
    source: "prefill:press",
    signal_type: "customer_win",
    title: "RailBank signs regional bank for settlement rails pilot",
    summary: "Fintech infra customer win; Ribbit-adjacent but still niche.",
    observed_at: "2026-07-28",
    raw: { prefill: true, early_signal: false, mainstream: false },
  },
  {
    id: "sig_hire_agentgate",
    company_id: "c_agentgate",
    company_name: "AgentGate",
    source: "prefill:hiring_proxy",
    signal_type: "hiring",
    title: "AgentGate opening 12 security + agent-runtime roles",
    summary: "Post-raise hiring wave — same company as Greylock funding signal.",
    observed_at: "2026-07-10",
    raw: { prefill: true, early_signal: false, mainstream: true },
  },
];
